import { CanActivate, Router, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
import { HttpClient, HttpParams, HttpHeaders } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from '../environments/environment';

@Injectable()
export class LocationsService {

    constructor(public httpClient: HttpClient,
                public router: Router
       ) {}

    public countriesAr = [
        'أرمينيا',
        'أروبا',
        'أستراليا',
        'النمسا',
        'أذربيجان',
        'جزر البهاما',
        'البحرين',
        'بنغلاديش',
        'بربادوس',
        'روسيا البيضاء',
        'بلجيكا',
        'بليز',
        'بوليفيا',
        'البوسنة والهرسك',
        'بوتسوانا',
        'البرازيل',
        'بروناي',
        'بلغاريا',
        'كمبوديا',
        'الكاميرون',
        'كندا',
        'جزر كايمان',
        'تشيلي',
        'الصين',
        'كولومبيا',
        'الكونغو',
        'كوستا ريكا',
        'كرواتيا',
        'كوبا',
        'قبرص',
        'جمهورية التشيك',
        'الدنمارك',
        'جمهورية الدومنيكان',
        'إكوادور',
        'مصر',
        'السلفادور',
        'إستونيا',
        'جزر فاروس',
        'فنلندا',
        'فرنسا',
        'بولينيزيا الفرنسية',
        'الغابون',
        'جورجيا',
        'ألمانيا',
        'غانا',
        'اليونان',
        'الأرض الخضراء',
        'غواديلوب',
        'غوام',
        'غواتيمالا',
        'غينيا',
        'هايتي',
        'المملكة الأردنية الهاشمية',
        'هندوراس',
        'هونج كونج',
        'هنغاريا',
        'أيسلندا',
        'الهند',
        'إندونيسيا',
        'إيران',
        'العراق',
        'أيرلندا',
        'جزيرة آيل أوف مان',
        'إسرائيل',
        'إيطاليا',
        'جامايكا',
        'اليابان',
        'كازاخستان',
        'كينيا',
        'كوسوفو',
        'الكويت',
        'لاتفيا',
        'لبنان',
        'ليبيا',
        'ليختنشتاين',
        'لوكسمبورج',
        'مقدونيا',
        'مدغشقر',
        'ماليزيا',
        'مالطا',
        'مارتينيك',
        'موريشيوس',
        'مايوت',
        'المكسيك',
        'منغوليا',
        'الجبل الأسود',
        'المغرب',
        'موزمبيق',
        'ميانمار [بورما]',
        'ناميبيا',
        'نيبال',
        'هولندا',
        'كاليدونيا الجديدة',
        'نيوزيلندا',
        'نيكاراغوا',
        'نيجيريا',
        'النرويج',
        'سلطنة عمان',
        'باكستان',
        'فلسطين',
        'بنما',
        'بابوا غينيا الجديدة',
        'باراغواي',
        'بيرو',
        'الفلبين',
        'بولندا',
        'البرتغال',
        'بورتوريكو',
        'جمهورية كوريا',
        'جمهورية ليتوانيا',
        'جمهورية مولدوفا',
        'رومانيا',
        'روسيا',
        'القديسة لوسيا',
        'سان مارينو',
        'المملكة العربية السعودية',
        'السنغال',
        'صربيا',
        'سنغافورة',
        'سلوفاكيا',
        'سلوفينيا',
        'جنوب أفريقيا',
        'إسبانيا',
        'سيريلانكا',
        'السودان',
        'سورينام',
        'سوازيلاند',
        'السويد',
        'سويسرا',
        'تايوان',
        'تنزانيا',
        'تايلاند',
        'ترينداد وتوباغو',
        'تونس',
        'ديك رومي',
        'جزر فيرجن الأمريكية',
        'أوكرانيا',
        'الإمارات العربية المتحدة',
        'المملكة المتحدة',
        'الولايات المتحدة الأمريكية',
        'أوروغواي',
        'فنزويلا',
        'فيتنام',
        'زامبيا',
        'زيمبابوي',
    ];
    public countriesEn = [
        'Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Botswana',
        'Brazil',
        'Brunei',
        'Bulgaria',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Cayman Islands',
        'Chile',
        'China',
        'Colombia',
        'Congo',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Cyprus',
        'Czech Republic',
        'Denmark',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Estonia',
        'Faroe Islands',
        'Finland',
        'France',
        'French Polynesia',
        'Gabon',
        'Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Greenland',
        'Guadeloupe',
        'Guam',
        'Guatemala',
        'Guinea',
        'Haiti',
        'Hashemite Kingdom of Jordan',
        'Honduras',
        'Hong Kong',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Isle of Man',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Kazakhstan',
        'Kenya',
        'Kosovo',
        'Kuwait',
        'Latvia',
        'Lebanon',
        'Libya',
        'Liechtenstein',
        'Luxembourg',
        'Macedonia',
        'Madagascar',
        'Malaysia',
        'Malta',
        'Martinique',
        'Mauritius',
        'Mayotte',
        'Mexico',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Mozambique',
        'Myanmar [Burma]',
        'Namibia',
        'Nepal',
        'Netherlands',
        'New Caledonia',
        'New Zealand',
        'Nicaragua',
        'Nigeria',
        'Norway',
        'Oman',
        'Pakistan',
        'Palestine',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Puerto Rico',
        'Republic of Korea',
        'Republic of Lithuania',
        'Republic of Moldova',
        'Romania',
        'Russia',
        'Saint Lucia',
        'San Marino',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'South Africa',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Swaziland',
        'Sweden',
        'Switzerland',
        'Taiwan',
        'Tanzania',
        'Thailand',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'U.S. Virgin Islands',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'United States',
        'Uruguay',
        'Venezuela',
        'Vietnam',
        'Zambia',
        'Zimbabwe',
    ];

    getCountries(language) {
        return this.httpClient.get(`${environment.api}locations/countries/${language}`);
    }

    getCities(countryId, language) {
        return this.httpClient.get(`${environment.api}locations/cities/${countryId}/${language}`);
    }

    getCountry(countryId, language) {
        return this.httpClient.get(`${environment.api}locations/country/${countryId}/${language}`);
    }

    getCity(cityId, language) {
        return this.httpClient.get(`${environment.api}locations/city/${cityId}/${language}`);
    }

}
